# Generated by Django 5.0 on 2024-07-24 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('SUV', 'Внедорожник'), ('wagon', 'Универсал'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('coupe', 'Купе'), ('cabrio', 'Кабриолет')]),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(blank=True, choices=[('rear', 'Задний'), ('front', 'Передний'), ('full', 'Полный')]),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electro', 'Электро')]),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('вариатор', 'CVT'), ('robot', 'Робот')]),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='volume',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
